# Generated by Django 4.0.3 on 2023-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userpredictmodel_delete_company_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predict/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPredictModel',
        ),
    ]
