# Generated by Django 5.0 on 2023-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_userimagemodel_delete_userpredictmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimagemodel",
            name="label",
            field=models.CharField(default="data", max_length=20),
        ),
    ]
